from testing import makeROCs_async

btruth='isB+isBB+isLeptonicB+isLeptonicB_C'
bbtruth ='isBB'
bleptruth ='isLeptonicB+isLeptonicB_C'

# high PT
makeROCs_async( ['/eos/cms/store/cmst3/group/dehep/DeepJet/Anna_DeepCSV/qcd_merged_CFR_PRED/tree_association.txt',
                '/eos/cms/store/cmst3/group/dehep/DeepJet/Predictions/Jan/DF_FT_fullRec_reg_BN/qcd_merged_PREDICTED/tree_association.txt'],
                 ['DeepCSV',
                  'DeepFlavour'],
                 ['prob_isB + prob_isBB',
                  'prob_isB + prob_isBB + prob_isLeptB',
                  'prob_isB + prob_isBB',
                  'prob_isB + prob_isBB + prob_isLeptB'],
                [btruth,
                 btruth,
                 btruth,
                 btruth],
                ['isUD + isS + isG',
                 'isUD + isS + isG',
                 'isC',
                 'isC'],
                ['blue',
                 'purple',
                 'blue,dashed',
                 'purple,dashed'],
                 "ROC_qcd_600_1000.pdf",
                 'jet_pt>600 && jet_pt<1000 && jet_eta>0',
                 True,
                 'QCD events',
                 "600 < jet p_{T} < 1000 [GeV], jet |#eta| < 2.4",
#                 "30 < jet p_{T} < 50 GeV}", 
                 '',
                 ['solid?L','dashed?C'],
                 True,
                 True,
                 "B efficiency"
                 )

# high PT
makeROCs_async( ['/eos/cms/store/cmst3/group/dehep/DeepJet/Anna_DeepCSV/qcd_merged_CFR_PRED/tree_association.txt',
                '/eos/cms/store/cmst3/group/dehep/DeepJet/Predictions/Jan/DF_FT_fullRec_reg_BN/qcd_merged_PREDICTED/tree_association.txt'],
                 ['DeepCSV',
                  'DeepFlavour'],
                 ['prob_isB + prob_isBB',
                  'prob_isB + prob_isBB + prob_isLeptB',
                  'prob_isB + prob_isBB',
                  'prob_isB + prob_isBB + prob_isLeptB'],
                [btruth,
                 btruth,
                 btruth,
                 btruth],
                ['isUD + isS + isG',
                 'isUD + isS + isG',
                 'isC',
                 'isC'],
                ['blue',
                 'purple',
                 'blue,dashed',
                 'purple,dashed'],
                 "ROC_qcd_300_600.pdf",
                 'jet_pt>300 && jet_pt < 600 && jet_eta>0',
                 True,
                 'QCD events',
                 "300 < jet p_{T} < 600 [GeV], jet |#eta| < 2.4",
#                 "30 < jet p_{T} < 50 GeV}", 
                 '',
                 ['solid?L','dashed?C'],
                 True,
                 True,
                 "B efficiency"
                 )

#QCD 150
makeROCs_async( ['/eos/cms/store/cmst3/group/dehep/DeepJet/Anna_DeepCSV/qcd_merged_CFR_PRED/tree_association.txt',
                '/eos/cms/store/cmst3/group/dehep/DeepJet/Predictions/Jan/DF_FT_fullRec_reg_BN/qcd_merged_PREDICTED/tree_association.txt'],
                 ['DeepCSV',
                  'DeepFlavour'],
                 ['prob_isB + prob_isBB',
                  'prob_isB + prob_isBB + prob_isLeptB',
                  'prob_isB + prob_isBB',
                  'prob_isB + prob_isBB + prob_isLeptB'],
                [btruth,
                 btruth,
                 btruth,
                 btruth],
                ['isUD + isS + isG',
                 'isUD + isS + isG',
                 'isC',
                 'isC'],
                ['blue',
                 'purple',
                 'blue,dashed',
                 'purple,dashed'],
                 "ROC_qcd_150_300.pdf",
                 'jet_pt>150 && jet_pt < 300 && jet_eta>0',
                 True,
                 'QCD events',
                 "150 < jet p_{T} < 300 [GeV], jet |#eta| < 2.4",
#                 "30 < jet p_{T} < 50 GeV}", 
                 '',
                 ['solid?L','dashed?C'],
                 True,
                 True,
                 "B efficiency"
                 )

# QCD only b
makeROCs_async( ['/eos/cms/store/cmst3/group/dehep/DeepJet/Anna_DeepCSV/qcd_merged_CFR_PRED/tree_association.txt',
                '/eos/cms/store/cmst3/group/dehep/DeepJet/Predictions/Jan/DF_FT_fullRec_reg_BN/qcd_merged_PREDICTED/tree_association.txt'],
                 ['DeepCSV',
                  'DeepFlavour'],
                 ['prob_isB',
                  'prob_isB+ prob_isLeptB',
                  'prob_isB',
                  'prob_isB+ prob_isLeptB'],
                ['isB+isLeptonicB+isLeptonicB_C',
                 'isB+isLeptonicB+isLeptonicB_C',
                 'isB+isLeptonicB+isLeptonicB_C',
                 'isB+isLeptonicB+isLeptonicB_C'],
                ['isUD + isS + isG',
                 'isUD + isS + isG',
                 'isC',
                 'isC'],
                ['blue',
                 'purple',
                 'blue,dashed',
                 'purple,dashed'],
                 "ROC_qcd_300_600_singleb.pdf",
                 'jet_pt>300 && jet_pt < 600 && jet_eta>0',
                 True,
                 'QCD events',
                 "300 < jet p_{T} < 600 [GeV], jet |#eta| < 2.4",
#                 "30 < jet p_{T} < 50 GeV}", 
                 '',
                 ['solid?L','dashed?C'],
                 True,
                 True,
                 "single b efficiency"
                 )

makeROCs_async( ['/eos/cms/store/cmst3/group/dehep/DeepJet/Anna_DeepCSV/qcd_merged_CFR_PRED/tree_association.txt',
                '/eos/cms/store/cmst3/group/dehep/DeepJet/Predictions/Jan/DF_FT_fullRec_reg_BN/qcd_merged_PREDICTED/tree_association.txt'],
                 ['DeepCSV',
                  'DeepFlavour'],
                 ['prob_isBB',
                  'prob_isBB',
                  'prob_isBB/(prob_isB+prob_isB)',
                  'prob_isBB/(prob_isBB+ prob_isB + prob_isLeptB)'],
                [bbtruth,
                 bbtruth,
                 bbtruth,
                 bbtruth],
                [
                 'isUD + isS + isG',
                 'isUD + isS + isG',
                 'isB+isLeptonicB+isLeptonicB_C',
                 'isB+isLeptonicB+isLeptonicB_C'
],
                ['blue',
                 'purple',
                 'blue,dashed',
                 'purple,dashed'],
                 "ROC_qcd_300_600_BB.pdf",
                 'jet_pt>300 && jet_pt < 600 && jet_eta>0',
                 True,
                 'QCD events',
                 "300 < jet p_{T} < 600 [GeV], jet |#eta| < 2.4",
#                 "30 < jet p_{T} < 50 GeV}", 
                 '',
                 ['solid?L','dashed?single b'],
                 True,
                 True,
                 "bb efficiency"
                 )

makeROCs_async( [
                '/eos/cms/store/cmst3/group/dehep/DeepJet/Predictions/Jan/DF_FT_fullRec_reg_BN/qcd_merged_PREDICTED/tree_association.txt'],
                 [
                  'DeepFlavour'],
                 ['prob_isLeptB/(prob_isLeptB+prob_isB)',
                  'prob_isLeptB'],
                [bleptruth,
                 bleptruth],
                ['isB',
                 'isUD + isS + isG'],
                ['purple,dashed',
                 'purple'],
                 "ROC_qcd_30_Blep.pdf",
                 'jet_pt>30 && jet_eta>0',
                 True,
                 'QCD events',
                 "30 < jet p_{T}[GeV], jet |#eta| < 2.4",
#                 "30 < jet p_{T} < 50 GeV}", 
                 '',
                 ['solid?L','dashed?b hadronic'],
                 True,
                 True,
                 "b leptonic efficiency"
                 )
