/*
 * version.h
 *
 *  Created on: 6 Nov 2019
 *      Author: jkiesele
 */

#ifndef DJCDEV_DEEPJETCORE_COMPILED_INTERFACE_VERSION_H_
#define DJCDEV_DEEPJETCORE_COMPILED_INTERFACE_VERSION_H_

#define DJCDATAVERSION ((float)2.0)



#endif /* DJCDEV_DEEPJETCORE_COMPILED_INTERFACE_VERSION_H_ */
